services:
  - type: web
    name: saferoute-backend
    runtime: docker
    rootDir: Rest-Api-main/Rest-Api
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?ssl-mode=REQUIRED&useSSL=true
      - key: SPRING_DATASOURCE_USERNAME
        value: gmbLF9WbF5jHwee.root
      - key: SPRING_DATASOURCE_PASSWORD
        value: dS2YnErdY4roadvp
      - key: SPRING_MAIL_PASSWORD
        sync: false # Set your Gmail App Password in Render Dashboard
      - key: JWT_SECRET
        generateValue: true

