# MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?ssl-mode=REQUIRED&useSSL=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gmbLF9WbF5jHwee.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dS2YnErdY4roadvp}
spring.profiles.active=dev
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8081

# JWT Setup
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=604800000

# JWT
app.jwt.secret=SafeRouteSecretKeyForJwtTokenGenerationChangeInProduction123
app.jwt.expiration-ms=604800000

# SafeRoute Simulation
saferoute.simulation.enabled=true

# Gmail SMTP Configuration
# Generate an App Password here: https://myaccount.google.com/apppasswords
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:biancamalhotra2004@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true